name: plant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  equatable: ^2.0.7

  # Networking
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1


  # Code Generation
  json_annotation: ^4.9.0

  # Routing
  auto_route: ^10.2.0

  # Storage
  shared_preferences: ^2.5.3

  # Dependency Injection
  get_it: ^9.0.5

  # UI
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  icons_launcher: ^3.0.3
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.11.1
  auto_route_generator: ^10.2.5
  mocktail: ^1.0.0
  bloc_test: ^9.1.7
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/home/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/paywall/
    - assets/svg/icons/

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto-Black.ttf
        weight: 800

icons_launcher:
  image_path: "assets/images/logo/logo.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/logo/logo.png"
      adaptive_icon_background: "0xFF28AF6E"
      adaptive_icon_foreground: "assets/images/logo/logo.png"
    ios:
      enable: true
      image_path: "assets/images/logo/logo.png"