name: plant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Networking
  dio: ^5.9.0
  connectivity_plus: ^7.0.0

  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Routing
  auto_route: ^10.2.0

  # Storage
  shared_preferences: ^2.5.3

  # Dependency Injection
  get_it: ^9.0.5

  # UI
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  auto_route_generator: ^10.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/images/logo/
    - assets/icons/
    - assets/images/illustrations/
    # - assets/images/plants/
    - assets/svg/
    # - assets/svg/icons/